import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

// The layering of ADR 0003, asserted rather than documented. Each entry is a
// group of import patterns forbidden to one part of src/. A file group gets one
// `no-restricted-imports` setting, so every group it is subject to is listed
// in it: flat config replaces a rule's options, it does not merge them.
const FEATURES = ['auth'];

const noFeatures = {
  group: ['@/features/*', '@/features/**', '**/features/*', '**/features/**'],
  message: 'Only app/ composes features. Cross-feature needs go through app/ or lib/.',
};

const noApp = {
  group: ['@/app/*', '@/app/**', '**/app/*', '**/app/**'],
  message: 'Nothing imports back up into app/ (ADR 0003).',
};

const noOtherFeature = (feature) => ({
  group: ['@/features/*', '@/features/**', `!@/features/${feature}`, `!@/features/${feature}/**`],
  message: 'A feature does not import another feature (ADR 0003). Go through app/ or lib/.',
});

// The mock ships in no production bundle (build plan Gate 2). Only tests, the
// mock itself and main.tsx's guarded dynamic import may reach it.
const noMock = {
  group: ['@/lib/testing/*', '@/lib/testing/**'],
  message: 'Production code does not import the mock. Tests may.',
};

const restrict = (...patterns) => ['error', { patterns }];

// The access token lives in memory only (ADR 0007). Nothing in src/ reaches
// for browser storage; tests may read it to prove that, and the mock may keep
// its own refresh tokens in it (MOCK_PERSISTENCE below).
const storageBan = {
  'no-restricted-globals': [
    'error',
    { name: 'localStorage', message: 'Nothing is kept in browser storage (ADR 0007).' },
    { name: 'sessionStorage', message: 'Nothing is kept in browser storage (ADR 0007).' },
  ],
  'no-restricted-properties': [
    'error',
    {
      object: 'window',
      property: 'localStorage',
      message: 'Nothing is kept in browser storage (ADR 0007).',
    },
    {
      object: 'window',
      property: 'sessionStorage',
      message: 'Nothing is kept in browser storage (ADR 0007).',
    },
    {
      object: 'globalThis',
      property: 'localStorage',
      message: 'Nothing is kept in browser storage (ADR 0007).',
    },
    {
      object: 'globalThis',
      property: 'sessionStorage',
      message: 'Nothing is kept in browser storage (ADR 0007).',
    },
  ],
};

const TESTS = ['src/**/*.test.ts', 'src/**/*.test.tsx', 'src/setupTests.ts'];

// The one production-shaped file allowed to touch storage: the mock keeps its
// refresh tokens across a reload there. It is mock code and never reaches a
// production bundle (build plan Gate 2); the access token is not in it.
const MOCK_PERSISTENCE = 'src/lib/testing/persistence.ts';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'docs',
      'playwright-report',
      'test-results',
      'blob-report',
      'dist-e2e',
      // Generated by `pnpm mock:worker`; MSW's own file, never edited here.
      'public/mockServiceWorker.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx', 'src/setupTests.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
    },
  },
  {
    files: ['vite.config.ts', 'playwright.config.ts'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: ['e2e/**/*.ts'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: [...TESTS, MOCK_PERSISTENCE],
    rules: storageBan,
  },
  {
    // ui/ knows tokens and nothing else. This is what makes the folder layout
    // a feature-module architecture rather than folders with nice names.
    // See BUILD-PLAN sections 4.2 and 10, and ADR 0003.
    files: ['src/ui/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': restrict(noFeatures, noApp, noMock),
    },
  },
  {
    files: ['src/ui/**/*.test.{ts,tsx}'],
    rules: {
      'no-restricted-imports': restrict(noFeatures, noApp),
    },
  },
  {
    // lib/ sits under everything; it imports nothing above it.
    files: ['src/lib/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': restrict(noFeatures, noApp),
    },
  },
  // One boundary per feature: adding a feature adds it to FEATURES (ADR 0003).
  ...FEATURES.flatMap((feature) => [
    {
      files: [`src/features/${feature}/**/*.{ts,tsx}`],
      rules: {
        'no-restricted-imports': restrict(noOtherFeature(feature), noApp, noMock),
      },
    },
    {
      files: [`src/features/${feature}/**/*.test.{ts,tsx}`],
      rules: {
        'no-restricted-imports': restrict(noOtherFeature(feature), noApp),
      },
    },
  ]),
  {
    files: ['src/app/**/*.{ts,tsx}'],
    ignores: TESTS,
    rules: {
      'no-restricted-imports': restrict(noMock),
    },
  },
  {
    files: ['eslint.config.js'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: globals.node,
    },
  },
  prettier,
);
